### PR TITLE
Sosie drowning newscheme openmp

### PR DESCRIPTION
**Pull request by pmathiot**
Hi Laurent, 

Here is my pull request to replace old drowning scheme (north fold not managed by it) with openMP instruction in case people want to speed it up. 
++

Pierre

### CODE REVIEW

**Comment by raphaeldussin** [comment]
Hi Pierre and Laurent,

this new algo looks great! I have been putting together a python package to do the "drown" in python (I'm using xESMF for all my remapping now) and compatible with xarray/dask (allows lazy evaluation) here:

https://github.com/raphaeldussin/HCtFlood

are you ok if I include this algo into it?

cheers,
Raf

**Comment by pmathiot** [comment]
Hi Raf,

If useful, fill free to pick it up. Don’t forget to mention it comes from SOSIE. Once it is done, could you share comparative plot of the different algo?

++

Pierre

**Comment by raphaeldussin** [comment]
@pmathiot sounds good! I'll keep you posted when I got it done.

**Comment by pmathiot** [comment]
Drowning algorithm change (better but slower). To balance this, openmp instructions had been added. If speed still an issue, consider decreasing the deflation level (one frame of ORCA12 drowning using 24 threads take ~30s to drown and 1 minute to read/write data). It is hard coded to 9.

**Pull request merged**
